# source = $HOME/.config/hypr/mocha.conf

$text = rgb(aaaaaa)
$textAlpha = aaaaaa

$accent = rgb(ff7f00)
$accentAlpha = ff7f00
#$font = JetBrainsMono Nerd Font
#$font = Lilex Nerd Font Light
$font = Teletext50 Extended
$font_large = Teletext50 ExtraCondensed

$text_size_small = 25
$text_size_large = 50

# GENERAL
general {
  hide_cursor = true
}

animations {
    enabled = false
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, .5, linear
    animation = fadeOut, 1, .5, linear
    animation = inputFieldDots, 0, 0, linear
}


auth {
  # see example from hyprlock docs
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning...
    retry_delay = 250 # in milliseconds
  }
}

# BACKGROUND
background {
  monitor =
  #path = $HOME/pictures/wallpaper
  #path = screenshot
  #blur_passes = 3
  #blur_size = 10
  #color = $base
  color = rgb(000000)
  
}

# LAYOUT
#label {
#  monitor =
#  text = Layout: $LAYOUT
#  color = $text
#  font_size = 25
#  font_family = $font
#  position = 30, -30
#  halign = left
#  valign = top
#}

# TIME
label {
  monitor =
  text = <span background="##$accentAlpha"> $TIME </span>
  #color = $text
  #color = $accent
  color = rgb(000000)
  font_size = $text_size_large
  font_family = $font_large
  position = 100, -145
  halign = left
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = $text_size_small
  font_family = $font
  position = 100, -100
  halign = left
  valign = top
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT";
  color = "$text";
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# USER AVATAR
#image {
#  monitor =
#  path = $HOME/.face
#  size = 100
#  border_color = $accent
#  border_size = 2
#  position = 0, 75
#  halign = center
#  valign = center
#}

# INPUT FIELD
input-field {
  monitor =
  size = 700, 90
  outline_thickness = -10
  rounding = -1

  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = false
  dots_text_format = *

  outer_color = $accent
  inner_color = rgba(00000000)  # $surface0
  padding = 0

  font_color = $text
  font_family = $font
  #placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  placeholder_text = <span>logged in as <span background="##$textAlpha" foreground="##000000">$USER</span>                            </span>
  text_align = left
  swap_font_color = true

  fade_on_empty = false
  hide_input = false
  check_color = $accent
  fail_color = rgb(ff0000)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  # numlock_color = $yellow
  position = 65, 50
  halign = left
  valign = bottom
}
